# Generated by Django 5.1.3 on 2025-02-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='in_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='maintenance_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
