# Generated by Django 5.1.3 on 2025-02-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_stockitem_in_maintenance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='notes',
            new_name='maintenance_notes',
        ),
    ]
